server:
  port: 8080

spring:
  application:
    name: SpringAiMcpTest
  ai:
    mcp:
      server:
        enabled: true
        name: book-mcp-server
        version: "1.0.0"
        type: SYNC
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
        sse-endpoint: /sse
        sse-message-endpoint: /mcp/message